//WalletReducer
export const SET_CURRENT_ACCOUNT = 'SET_CURRENT_ACCOUNT'
export const SET_ACCOUNTS = 'SET_ACCOUNTS'
export const SET_NETWORK_ID = 'SET_NETWORK_ID'
export const SET_ENCRYPT = 'SET_ENCRYPT'
export const SET_WALLET = 'SET_WALLET'
export const SET_MNEMONIC = 'SET_MNEMONIC'
//WalletMain
export const SET_PROFILE_MODAL_VISIABLE = 'SET_PROFILE_MODAL_VISIABLE'
export const SET_SEND_PASSWORD_MODAL_VISIABLE = 'SET_SEND_PASSWORD_MODAL_VISIABLE'
export const SET_NETWORK_MODAL_VISIABLE = 'SET_NETWORK_MODAL_VISIABLE'
export const SET_SHOW_BALANCE_LOADING = 'SET_SHOW_BALANCE_LOADING'
//selectAccounts
export const SELECT_ACCOUNT = 'SELECT_ACCOUNT'
//Open Wallet
export const SET_OPEN_PASSWORD = 'SET_OPEN_PASSWORD'
//Import Wallet
export const SET_IMPORT_MNEMONIC = 'SET_IMPORT_MNEMONIC'
//Create Wallet
export const SET_MNEMONIC_CN = 'SET_MNEMONIC_CN'
export const SET_MNEMONIC_EN = 'SET_MNEMONIC_EN'
export const SET_USE_MNEMONIC = 'SET_USE_MNEMONIC'
export const SET_DEFAULT_MNEMONIC = 'SET_DEFAULT_MNEMONIC'
export const SET_LANG = 'SET_LANG'
export const SET_RANDOM_MNEMONIC = 'SET_RANDOM_MNEMONIC'
//Send
export const SET_FROM_ADDRESS = 'SET_FROM_ADDRESS'
export const SET_TO_ADDRESS = 'SET_TO_ADDRESS'
export const SET_AMOUNT = 'SET_AMOUNT'
export const SET_BALANCE = 'SET_BALANCE'
export const SET_ETH_PRICE = 'SET_ETH_PRICE'
export const SET_NOTE = 'SET_NOTE'
export const SET_GAS_PRICE = 'SET_GAS_PRICE'
export const SET_MY_GAS_PRICE = 'SET_MY_GAS_PRICE'
export const SET_GAS_LIMIT = 'SET_GAS_LIMIT'
export const SET_TX = 'SET_TX'
export const SET_RECEIPT = 'SET_RECEIPT'
export const CLEAR_SEND = 'CLEAR_SEND'
//Gesture
export const SET_GESTURE = 'SET_GESTURE'
